<a href="https://colab.research.google.com/github/RohanDevu/ML_24AG5A6620/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello Rohan")

Hello Rohan


In [3]:
import numpy as np

CREATING 1D ARRAY

In [5]:
list1=[2,4,6,8]
array1=np.array(list1)
print(array1)

[2 4 6 8]


CREATING 2D ARRAY

In [9]:
list1=([1,2,3,4],
           [5,6,7,8])
array2 = np.array(list1)
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


CREATING 3D ARRAY

In [18]:
array3 = np.array([[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],

                 [[13,14,15,16],
                  [17,18,19,20],
                  [21,22,23,24]]])

print(array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


USING ATTRIBUTES

Finding the Datatype of the Arrays

In [25]:
print(array1.dtype)

int64


In [20]:
print(array2.dtype)

int64


In [21]:
print(array3.dtype)

int64


Finding the Dimensions of the Arrays

In [22]:
print(array1.ndim)

1


In [23]:
print(array2.ndim)

2


In [24]:
print(array3.ndim)

3


Finding the Size of the Arrays

In [26]:
print(array1.size)

4


In [27]:
print(array2.size)

8


In [28]:
print(array3.size)

24


Finding the Shape of the Arrays

In [29]:
print(array3.shape)

(2, 3, 4)


In [30]:
print(array2.shape)

(2, 4)


In [31]:
print(array3.shape)

(2, 3, 4)


Finding the Itemsize of the Arrays

In [35]:
print(array1.itemsize)

8


In [37]:
print(array2.itemsize)

8


In [38]:
print(array3.itemsize)

8


Finding the Data of the Arrays

In [39]:
print(array1.data)

In [40]:
print(array2.data)

In [41]:
print(array3.data)

Finding the Mean of the Arrays

In [43]:
marks = np.array([76,78,81,95,69])
mean_marks = np.mean(marks)
print(mean_marks)

79.8


Finding the Deviation of the Arrays

In [44]:
marks = np.array([76,78,81,95,69])
std_marks = np.std(marks)
print(std_marks)

8.565045242145542


Finding the Minimum Percentile of the Arrays

In [45]:
marks = np.array([76,78,81,95,69])
std_marks = np.min(marks)
print(std_marks)

69


Finding the Maximum Percentile of the Arrays

In [46]:
marks = np.array([76,78,81,95,69])
std_marks = np.max(marks)
print(std_marks)

95
