<a href="https://colab.research.google.com/github/RohanDevu/ML_24AG5A6620/blob/main/statistical_measures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**STATISTICAL MEASURES**

In [2]:
import numpy as np
from statistics import mean, median, mode

#Example data
data = [2,4,4,4,5,5,7,9]

#Central Tendency Measures
print("Mean:", mean(data))
print("Median:", median(data))
print("Mode:", mode(data))

#Measures of Dispersion
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))

Mean: 5
Median: 4.5
Mode: 4
Variance: 4.0
Standard Deviation: 2.0


**1. Number Functions**

In [7]:
import math
print(math.ceil(2.9))
print(math.floor(12.7))
print(math.trunc(8.9))

3
12
8


**2. Power and Logarithmic Functions**

In [10]:
print(math.pow(5,3))
print(math.sqrt(9))
print(math.exp(5))
print(math.log(2,2))

125.0
3.0
148.4131591025766
1.0


**3. Trignometric Functions**

In [20]:
print(math.sin(math.pi/8))
print(math.cos(45))
print(math.tan(math.pi/4))

print(math.radians(60))
print(math.degrees(math.pi))

0.3826834323650898
0.5253219888177297
0.9999999999999999
1.0471975511965976
180.0


**4. Special Functions**

In [27]:
print(math.factorial(6))
print(math.gcd(5,125))
print(math.fabs(-8.55))

720
5
8.55


**5. Constants**

In [29]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045


**SciPy**

In [32]:
#print hte constant value of pi:
from scipy import constants

print(constants.pi)

print(constants.yotta)
print(constants.zetta)
print(constants.exa)
print(constants.peta)
print(constants.tera)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.hecto)
print(constants.deka)
print(constants.deci)
print(constants.centi)
print(constants.milli)
print(constants.micro)
print(constants.nano)
print(constants.pico)
print(constants.femto)
print(constants.atto)
print(constants.zepto)

3.141592653589793
1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [33]:
#Binary Prefixes:
#Return the specified unit in bytes (e.g. kibi returns 1024)

print(constants.kibi)
print(constants.mebi)
print(constants.gibi)
print(constants.tebi)
print(constants.pebi)
print(constants.exbi)
print(constants.zebi)
print(constants.yobi)

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


In [34]:
#Connected Components
#Find all of the connected components with the connected() method.

import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])
newarr = csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


**Dijkstra**

In [35]:
#Find the shortest path from element 1 to 2:

import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [36]:
#Floyd Warshall
#Use the floyd_warshall() method to find shortest path between all pairs of elements.

#Find the shortest path between all pairs of elements:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [37]:
#Bellman Ford
#The bellman_ford() method can also find the shortest path between all pairs of elements, but this method can handle negaitve weights as well.

#Find shortest path from element 1 to 2 with given graph with a negative weight:

import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))
